apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-y17r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-y17r
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-y17r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-y17r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-y17r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fnlf-tenant/rhtap-demo-app/hacbs-test-project-y17r@sha256:f5c7d466c524671e97b8cfd0faeff0dd35bd59b7a4363504b9f6dcf06165d950
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
